name: Speedtest
services:
  Speedtest:
    image: openspeedtest/latest
    container_name: Speedtest
    restart: unless-stopped
    hostname: speedtest
    networks:
      - Speedtest
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.20"
    #       memory: 80M

networks:
  Speedtest:
    name: Speedtest
    external: true
